// Code generated by cligen; DO NOT EDIT.

package cli

import (
	"fmt"
)

type FlagDef struct {
	Name  string
	Short string
	Type  string
	Desc  string
}

type ArgDef struct {
	Name string
	Type string
	Desc string
}

type CommandDef struct {
	Name        string
	FullCommand string
	Desc        string
	Dangerous   bool
	Args        []ArgDef
	Flags       []FlagDef
	Subs        []CommandDef
	Examples    []string
}

type TopicDef struct {
	Name string
	Desc string
	Text string
}

type GlobalFlags struct {
	Help    bool
	Verbose bool
}

type ProjectInitParams struct {
	GlobalFlags
	Path string
}

type UserAddParams struct {
	GlobalFlags
	Name string
}

type Handlers[T any] interface {
	Help(args []string) (T, error)
	RunProjectInit(params *ProjectInitParams) (T, error)
	RunUserAdd(params *UserAddParams) (T, error)
}

type Action[T any] func(h Handlers[T]) (T, error)

var CliGlobalFlags = []FlagDef{
	{Name: "help", Short: "h", Type: "bool", Desc: "Show help information"},
	{Name: "verbose", Short: "v", Type: "bool", Desc: "Enable verbose output"},
}

var CliTopics = []TopicDef{}

var CliCommands = []CommandDef{

	CommandDef{
		Name:        "help",
		FullCommand: "help",
		Desc:        "Show help information",
		Dangerous:   true,
	},

	CommandDef{
		Name:        "user",
		FullCommand: "user",
		Desc:        "Manage users",
		Dangerous:   true,
		Subs: []CommandDef{

			CommandDef{
				Name:        "add",
				FullCommand: "user/add",
				Desc:        "Add a user",
				Dangerous:   true,
				Args: []ArgDef{
					{Name: "name", Type: "string", Desc: "User name"},
				},
				Examples: []string{
					"app user add alice",
				},
			},
		},
	},

	CommandDef{
		Name:        "project",
		FullCommand: "project",
		Desc:        "Manage projects",
		Dangerous:   true,
		Subs: []CommandDef{

			CommandDef{
				Name:        "init",
				FullCommand: "project/init",
				Desc:        "Initialize a project",
				Dangerous:   true,
				Args: []ArgDef{
					{Name: "path", Type: "string", Desc: "Project path"},
				},
				Examples: []string{
					"app project init ./demo",
				},
			},
		},
	},
}

var CliAppName = "example"
var CliTagline = "Minimal CLI sample"

type Invocation struct {
	Command *CommandDef
	Args    map[string]string
	Flags   map[string]any
}

func Parse[T any](args []string) (Action[T], *CommandDef, error) {

	var gf GlobalFlags
	remaining := ProcessGlobalFlags(args, &gf)

	if len(remaining) > 0 && remaining[0] == "help" {
		gf.Help = true
		remaining = remaining[1:]
	}

	if gf.Help || len(remaining) == 0 {
		var helpCmd *CommandDef
		for i := range CliCommands {
			if CliCommands[i].Name == "help" {
				helpCmd = &CliCommands[i]
				break
			}
		}
		return func(h Handlers[T]) (T, error) {
			return h.Help(remaining)
		}, helpCmd, nil
	}

	resolvedCmd, remArgs, err := Resolve(CliCommands, remaining)
	if err != nil {
		return nil, nil, err
	}

	inv := &Invocation{Command: resolvedCmd, Args: make(map[string]string), Flags: make(map[string]any)}
	if err := ParseParams(inv, resolvedCmd, remArgs); err != nil {
		return nil, resolvedCmd, err
	}

	switch resolvedCmd.FullCommand {
	case "project/init":
		return handleProjectInit[T](inv, gf), resolvedCmd, nil
	case "user/add":
		return handleUserAdd[T](inv, gf), resolvedCmd, nil
	default:
		if len(resolvedCmd.Subs) > 0 {
			return func(h Handlers[T]) (T, error) {
				return h.Help(remaining)
			}, resolvedCmd, nil
		}
		return nil, resolvedCmd, fmt.Errorf("no handler for command: %s", resolvedCmd.FullCommand)
	}
}

func ApplyGlobalFlag(g *GlobalFlags, name string, val any) {
	switch name {
	case "help":
		if b, ok := val.(bool); ok {
			g.Help = b
		}
	case "verbose":
		if b, ok := val.(bool); ok {
			g.Verbose = b
		}
	}
}
func handleProjectInit[T any](inv *Invocation, gf GlobalFlags) Action[T] {
	params := &ProjectInitParams{}
	params.GlobalFlags = gf
	params.Path = inv.Args["path"]
	return func(h Handlers[T]) (T, error) {
		return h.RunProjectInit(params)
	}
}
func handleUserAdd[T any](inv *Invocation, gf GlobalFlags) Action[T] {
	params := &UserAddParams{}
	params.GlobalFlags = gf
	params.Name = inv.Args["name"]
	return func(h Handlers[T]) (T, error) {
		return h.RunUserAdd(params)
	}
}
